version: "3.8"
services:
    feService:
        container_name: feService
        volumes:
            - ./:/app
        ports:
            - "80:3000"
        image: node:slim
        command: bash -c "cd /app && npm install && npm run start"
        environment:
            - REACT_APP_API_TEXT="http://172.31.2.123:4000/text"
            - REACT_APP_API_IMG="http://172.31.2.123:4000/img"
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    database:
        driver: local
